/*
 * ultrasonic.h
 *
 *  Created on: Oct 15, 2023
 *      Author: hp
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define TRIGGER_PORT PORTB_ID
#define TRIGGER_PIN PIN5_ID
#define PRESCALER F_CPU_8
/*
 * the constant that will be used to get the distance from the timer value
 */
#define CONST (0.017)

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/
/*
 * Description :
 * 1-Initialize the ICU driver with required settings.
 * 2-Setup the ICU call back function.
 * 3-Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void);

/*
 * Description :
 * 1-Send the Trigger pulse to the Ultrasonic.
 */

void Ultrasonic_Trigger(void);

/*
 * Description :
 * 1-Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2-Start the measurements by the ICU from this moment.
 * 3-Return The measured distance in Centimeter.
 */

uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * 1-This is the call back function called by the ICU driver.
 * 2-This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */

void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
